### ISSUE TITLE
3.7.0: IllegalArgumentException: pointerIndex out of range

### ISSUE THREAD

**Issue by RocketRider** [davemorrissey/subsampling-scale-image-view#353]
I upgraded to the new version 3.7.0 and found a new issue.
When I zoom while an image is still loading I get the following exception:

> java.lang.IllegalArgumentException: pointerIndex out of range
> at android.view.MotionEvent.nativeGetAxisValue(Native Method)
> at android.view.MotionEvent.getX(MotionEvent.java:2111)
> at android.support.v4.view.ViewPager.onInterceptTouchEvent(ViewPager.java:2064)
> at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2313)
> at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2712)
> at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2428)
> at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2712)
> at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2428)
> at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2712)
> at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2428)
> at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2712)
> at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2428)
> at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2712)
> at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2428)
> at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2679)
> at com.android.internal.policy.impl.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1797)
> at android.app.Activity.dispatchTouchEvent(Activity.java:2878)
> at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:68)
> at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2640)
> at android.view.View.dispatchPointerEvent(View.java:9234)
> at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4785)
> at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4623)
> at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4174)
> at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4227)
> at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4193)
> at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4303)
> at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4201)
> at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4360)
> at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4174)
> at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4227)
> at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4193)
> at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4201)
> at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4174)
> at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:6652)
> at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:6536)
> at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:6507)
> at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:6742)
> at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
> at android.view.InputEventReceiver.nativeConsumeBatchedInputEvents(Native Method)
> at android.view.InputEventReceiver.consumeBatchedInputEvents(InputEventReceiver.java:176)
> at android.view.ViewRootImpl.doConsumeBatchedInput(ViewRootImpl.java:6713)
> at android.view.ViewRootImpl$ConsumeBatchedInputRunnable.run(ViewRootImpl.java:6765)
> at android.view.Choreographer$CallbackRecord.run(Choreographer.java:777)
> at android.view.Choreographer.doCallbacks(Choreographer.java:590)
> at android.view.Choreographer.doFrame(Choreographer.java:558)
> at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:763)
> at android.os.Handler.handleCallback(Handler.java:739)
> at android.os.Handler.dispatchMessage(Handler.java:95)
> at android.os.Looper.loop(Looper.java:145)
> at android.app.ActivityThread.main(ActivityThread.java:6117)
> at java.lang.reflect.Method.invoke(Native Method)
> at java.lang.reflect.Method.invoke(Method.java:372)
> at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(Zygot
> 02-02 06:56:29.360 2975-3425/? W/ActivityManager: Force finishing activity

**Comment by davemorrissey** [comment]
Can you try to reproduce this with 3.6.0? There's nothing related to this library in the stack trace and I can't reproduce this problem.

**Comment by RocketRider** [comment]
With 3.6.0 it is working fine. The issue came with 3.7.0. I downgraded again and the app is working.

**Comment by davemorrissey** [comment]
Is your view in a ViewPager or DrawerLayout?

**Comment by davemorrissey** [comment]
Can you please post your code for initialising the view, and the layout XML? I can't reproduce any of these problems.

**Comment by RocketRider** [comment]
It is inside a Viewpager.

```
    @Override
        public ImageItem instantiateItem(final ViewGroup container, final int position) {
            final ImageItem imageItem = items.get(position);
            final ImageMediaItem imageMediaItem = imageItem.mediaItem;

            final View viewLayout = inflater.inflate(R.layout.media_image_item, container, false);

            final SubsamplingScaleImageView imageView = viewLayout.findViewById(R.id.imageView);
            imageView.setImage(ImageSource.uri(imageMediaItem.getPath()));
            ....
    }
```



```
<FrameLayout
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent">

    <com.davemorrissey.labs.subscaleview.SubsamplingScaleImageView
        android:id="@+id/imageView"
        android:layout_width="match_parent"
        android:layout_height="match_parent"/>

    <RelativeLayout
        android:id="@+id/imageFooter"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:layout_gravity="bottom"
        android:background="@color/airbus_black_alpha"
        android:padding="16dp">

        <TextView
            android:id="@+id/imagePosition"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:layout_alignParentRight="true"
            android:textColor="@color/airbus_white"
            android:textSize="16sp"
            android:visibility="gone"
            tools:text="position"
            tools:visibility="visible"/>

        <TextView
            android:id="@+id/imageDescription"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:layout_toLeftOf="@id/imagePosition"
            android:textColor="@color/airbus_white"
            android:textSize="16sp"
            android:visibility="gone"
            tools:text="Description"
            tools:visibility="visible"/>

        <TextView
            android:id="@+id/imageDTG"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:layout_below="@id/imageDescription"
            android:layout_toLeftOf="@id/imagePosition"
            android:textColor="@color/airbus_white"
            android:textSize="16sp"
            android:visibility="gone"
            tools:text="Date/Time"
            tools:visibility="visible"/>
    </RelativeLayout>
</FrameLayout>

```

**Comment by davemorrissey** [comment]
I assume `ImageMediaItem.getPath()` returns a string? Does that string start with `android.resource://`? If not I can't explain why you're seeing the `Failed to initialise decoder` message.

For the other crash, have a look at the Issues with ViewGroups section on this page and see if that can fix the problem: https://github.com/chrisbanes/PhotoView

**Comment by RocketRider** [comment]
ImageMediaItem.getPath() returns a path to the file:
/storage/sdcard/Pictures/Pictures/1426520776827815208915317789357695820350.jpg

The URI from ImageSource.uri looks like this: 
file:///storage/sdcard/Pictures/Pictures/1426520776827815208915317789357695820350.jpg

Thank you for the link. I will take a look.

**Comment by davemorrissey** [comment]
I've set my sample app up to pick images from the photo gallery and load images using their URI e.g. `file:///storage/emulated/0/DCIM/Camera/IMG_20170824_191737.jpg` and this works perfectly, with no error logs. I can't explain why you're seeing `Failed to initialise bitmap decoder` - are you able to debug your app to see how `SkiaImageRegionDecoder` reaches line 70?

**Comment by RocketRider** [comment]
Not sure where it comes from. Even when I don't load any image it still gets called after the inflate of the view.
The uri looks correct but I can't find any resource with that id: android.resource://com.xx.yy/2131493061
![image](https://user-images.githubusercontent.com/1881640/31998134-f508bd0e-b98e-11e7-9e9f-3ac8bf6596c9.png)

**Comment by davemorrissey** [comment]
Please can you try version 3.7.1?

**Comment by RocketRider** [comment]
With the version 3.7.1. Both issues seem to be fixed.

**Comment by davemorrissey** [comment]
Very strange. I rolled back the PR I merged into 3.7.0 which updated gradle and Android tools, and that fixed it. Thanks for letting me know.

**Comment by davemorrissey** [comment]
Release 3.7.2 is available and should fix this problem. The 3.7.0 release contained a jar instead of an aar, so was missing the meta information for the custom attributes. 3.7.2 uses updated build scripts but contains the aar.

**Comment by RocketRider** [comment]
Thank you, I will try it

**Comment by yangjiantao** [comment]
v3.7.2 is still crashed .@davemorrissey
`FATAL EXCEPTION: main
                                                                                            Process: com.davemorrissey.labs.subscaleview.sample, PID: 19659
                                                                                            java.lang.IllegalArgumentException: pointerIndex out of range
                                                                                                at android.view.MotionEvent.nativeGetAxisValue(Native Method)
                                                                                                at android.view.MotionEvent.getX(MotionEvent.java:2201)
                                                                                                at android.support.v4.view.ViewPager.onInterceptTouchEvent(ViewPager.java:2092)
                                                                                                at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2504)
                                                                                                at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2961)
                                                                                                at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2650)
                                                                                                at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2961)
                                                                                                at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2650)
                                                                                                at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2961)
                                                                                                at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2650)
                                                                                                at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2961)
                                                                                                at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2650)
                                                                                                at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:445)
                                                                                                at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1828)
                                                                                                at android.app.Activity.dispatchTouchEvent(Activity.java:3292)
                                                                                                at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:407)
                                                                                                at android.view.View.dispatchPointerEvent(View.java:11960)
                                                                                                at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4776)
                                                                                                at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4590)
                                                                                                at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4128)
                                                                                                at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4181)
                                                                                                at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4147)
                                                                                                at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4274)
                                                                                                at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4155)
                                                                                                at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4331)
                                                                                                at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4128)
                                                                                                at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4181)
                                                                                                at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4147)
                                                                                                at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4155)
                                                                                                at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4128)
                                                                                                at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:6642)
                                                                                                at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:6616)
                                                                                                at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:6577)
                                                                                                at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:6745)
                                                                                                at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
                                                                                                at android.view.InputEventReceiver.nativeConsumeBatchedInputEvents(Native Method)
                                                                                                at android.view.InputEventReceiver.consumeBatchedInputEvents(InputEventReceiver.java:176)
                                                                                                at android.view.ViewRootImpl.doConsumeBatchedInput(ViewRootImpl.java:6716)
                                                                                                at android.view.ViewRootImpl$ConsumeBatchedInputRunnable.run(ViewRootImpl.java:6768)
                                                                                                at android.view.Choreographer$CallbackRecord.run(Choreographer.java:911)
                                                                                                at android.view.Choreographer.doCallbacks(Choreographer.java:723)
                                                                                                at android.view.Choreographer.doFrame(Choreographer.java:652)
                                                                                                at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:897)
                                                                                                at android.os.Handler.handleCallback(Handler.java:789)
                                                                                                at android.os.Handler.dispatchMessage(Handler.java:98)
                                                                                                at android.os.Looper.loop(Looper.java:164)
                                                                                                at android.app.ActivityThread.main(ActivityThread.java:6541)
                                                                                                at java.lang.reflect.Method.invoke(Native Method)
                                                                                                at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
                                                                                                at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)`

**Comment by fanpengfei1993** [comment]
E/SubsamplingScaleImageView: Failed to initialise bitmap decoder
                                                                                   java.io.FileNotFoundException: No content provider: http://192.168.50.123:8080/public/0B612B6BA1F05DF8E.jpg
                                                                                       at android.content.ContentResolver.openTypedAssetFileDescriptor(ContentResolver.java:1142)
                                                                                       at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:993)
                                                                                       at android.content.ContentResolver.openInputStream(ContentResolver.java:713)
                                                                                       at com.davemorrissey.labs.subscaleview.decoder.SkiaImageRegionDecoder.init(SkiaImageRegionDecoder.java:67)
                                                                                       at com.davemorrissey.labs.subscaleview.SubsamplingScaleImageView$TilesInitTask.doInBackground(SubsamplingScaleImageView.java:1515)
                                                                                       at com.davemorrissey.labs.subscaleview.SubsamplingScaleImageView$TilesInitTask.doInBackground(SubsamplingScaleImageView.java:1490)
                                                                                       at android.os.AsyncTask$2.call(AsyncTask.java:316)
                                                                                       at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                                       at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:255)
                                                                                       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
                                                                                       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
                                                                                       at java.lang.Thread.run(Thread.java:776)

**Comment by BartNijland91** [comment]
3.10.0 also still crashing with the same issue

**Comment by akrezic1** [comment]
Seems like the actual issue is in ViewPager implementation. I've managed to fix it with solution from other repo issue:
https://github.com/chrisbanes/PhotoView/issues/31#issuecomment-19803926
